### ISSUE TITLE
Installer crashes when something other then a zip is selected for existing vscode download

### ISSUE THREAD

**Issue by ThadHouse** [wpilibsuite/WPILibInstaller-Avalonia#83] opened 2020-11-03 14:23 UTC

**Comment by Daltz333** [comment] 2020-11-03 14:49
Duplicate of #3

**Comment by Starlight220** [comment] 2020-11-03 15:00
It should be documented that the VS Code options in the installer don't install VS Code itself; they download the VS Code installer (yeah, the word "install" appears in this sentence *way* too much).

**Closed** 2020-11-12 00:34 UTC
Labels: bug
