### ISSUE TITLE
The beta WPILib Linux installer errors out if  `$HOME/.local/share/applications` does not exist.

### ISSUE THREAD

**Issue by williamhaley** [wpilibsuite/WPILibInstaller-Avalonia#142] opened 2021-01-01 18:33 UTC
**Describe the bug**

The beta WPILib Linux installer errors out if  `$HOME/.local/share/applications` does not exist.

```
System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/will/.local/share/applications/FRC VS Code 2021.desktop'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.File.AsyncStreamWriter(String path, Encoding encoding, Boolean append)
   at System.IO.File.WriteAllTextAsync(String path, String contents, Encoding encoding, CancellationToken cancellationToken)
   at System.IO.File.WriteAllTextAsync(String path, String contents, CancellationToken cancellationToken)
   at WPILibInstaller.ViewModels.InstallPageViewModel.RunShortcutCreator(CancellationToken token)
   at WPILibInstaller.ViewModels.InstallPageViewModel.RunInstall()
   at WPILibInstaller.ViewModels.InstallPageViewModel.<>c__DisplayClass24_0.<<-ctor>g__installFunc|0>d.MoveNext()
```

**To Reproduce**

Run the [v2021.1.1-beta-4 installer](https://github.com/wpilibsuite/allwpilib/releases/tag/v2021.1.1-beta-4) on a fresh Debian Buster VM with `Download VS Code for Single Install` and all items checked for `Select the items you would like to install.`

**Expected behavior**

The installer either creates the necessary path for the shortcut or otherwise gracefully handles if the shortcut path does not exist.

**Screenshots**

![error](https://user-images.githubusercontent.com/1851748/103444249-821ad280-4c2c-11eb-81ba-0f9864d7c160.png)

**Desktop (please complete the following information):**

 - OS: Debian Buster 10.7

**Additional context**

This error does not seem to be a huge deal. I think it's probably one of the last steps run and WPILib _seems_ fine after this error is thrown, but obviously this is not an ideal user experience.

**Comment by sciencewhiz** [comment] 2021-01-01 18:36
Duplicate of #138

**Closed by sciencewhiz** 2021-01-01 18:36 UTC
